// <auto-generated />
namespace HFSRBO.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_col2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_col2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903060254568_change_col2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
