// <auto-generated />
namespace HFSRBO.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_change_col : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_change_col));
        
        string IMigrationMetadata.Id
        {
            get { return "201903050520470_add_change_col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
