// <auto-generated />
namespace HFSRBO.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class new_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(new_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201903120550310_new_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
