// <auto-generated />
namespace HFSRBO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_datatype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_datatype));
        
        string IMigrationMetadata.Id
        {
            get { return "201901080642311_change_datatype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
