// <auto-generated />
namespace HFSRBO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class remove_col : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_col));
        
        string IMigrationMetadata.Id
        {
            get { return "201901240140406_remove_col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
