// <auto-generated />
namespace HFSRBO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201901080702516_change_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
